# Generated by Django 2.2.6 on 2019-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('publisth_date', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=256)),
            ],
        ),
    ]
