# Generated by Django 2.2.6 on 2019-10-06 16:02

from django.db import migrations, models
import linux_in_schools.models


class Migration(migrations.Migration):

    dependencies = [
        ('linux_in_schools', '0002_auto_20191006_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='list_picture',
            field=models.ImageField(blank=True, null=True, upload_to=linux_in_schools.models.article_upload_to),
        ),
    ]
