# Generated by Django 2.2.6 on 2019-10-06 11:22

from django.db import migrations, models
import pdf_list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=126)),
                ('pdf_file', models.FileField(upload_to=pdf_list.models.pdf_upload_to)),
            ],
        ),
    ]
